feat: implement sprint requirements
agluh/java-shareit pull request #4
Opened 2022-08-16 07:25 UTC by agluh

Breaks app into two parts: server and gateway.

2022-08-16 16:17 UTC, kukolev requested changes

2022-08-16 16:17 UTC, kukolev commented on server/src/main/java/ru/practicum/shareitserver/booking/repository/BookingRepository.java
> +    List<Booking> findBookingsByBookerIdAndStatusOrderByStartDesc(long userId,
По моему такие методы очень плохо читаются в коде. Будет лучше, если названия будут короткими, а логика поиска будет реализована в `@Query`

2022-08-17 06:31 UTC, agluh commented on server/src/main/java/ru/practicum/shareitserver/booking/repository/BookingRepository.java
> +    List<Booking> findBookingsByBookerIdAndStatusOrderByStartDesc(long userId,
Готово

2022-08-17 11:16 UTC, kukolev approved these changes

2022-08-17 11:54 UTC, merged